# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_reg_machine_btn(object):
    def setupUi(self, reg_machine_btn):
        reg_machine_btn.setObjectName("reg_machine_btn")
        reg_machine_btn.resize(815, 602)
        self.centralwidget = QtWidgets.QWidget(reg_machine_btn)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 130, 25))
        self.pushButton.setObjectName("pushButton")
        reg_machine_btn.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(reg_machine_btn)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        reg_machine_btn.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(reg_machine_btn)
        self.statusbar.setObjectName("statusbar")
        reg_machine_btn.setStatusBar(self.statusbar)
        self.actionRegister_Machine = QtWidgets.QAction(reg_machine_btn)
        self.actionRegister_Machine.setObjectName("actionRegister_Machine")
        self.menuMenu.addAction(self.actionRegister_Machine)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(reg_machine_btn)
        QtCore.QMetaObject.connectSlotsByName(reg_machine_btn)

    def retranslateUi(self, reg_machine_btn):
        _translate = QtCore.QCoreApplication.translate
        reg_machine_btn.setWindowTitle(_translate("reg_machine_btn", "MainWindow"))
        self.pushButton.setText(_translate("reg_machine_btn", "Register Machine"))
        self.menuMenu.setTitle(_translate("reg_machine_btn", "Menu"))
        self.actionRegister_Machine.setText(_translate("reg_machine_btn", "Register Machine"))
        self.pushButton.clicked.connect(self.register_machine)

    def register_machine(self):
        ip, done1 = QtWidgets.QInputDialog.getText(self, 'Input Dialog', 'Enter Machine IP:')

        name, done2 = QtWidgets.QInputDialog.getText(self, 'Input Dialog', 'Enter Username:')

        password, done3 = QtWidgets.QInputDialog.getText(self, 'Input Dialog', 'Enter Password:')

        if done1 and done2 and done3:
            self.pushButton.hide()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    reg_machine_btn = QtWidgets.QMainWindow()
    ui = Ui_reg_machine_btn()
    ui.setupUi(reg_machine_btn)
    reg_machine_btn.show()
    sys.exit(app.exec_())
